{
 "title": "Purple Air",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Current AQI",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "purpleair_aqi_pm2_5_10_minute{conversion=\"None\"}",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "purpleair_temp_f - 8", "legendFormat": "{{label}}" }
   ]
  },
  {
   "title": "Current Pressure",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "purpleair_pressure", "legendFormat": "{{label}}" }
   ]
  },
  {
   "title": "Humidity",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_max(purpleair_humidity + 4, 100)",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "AQI History",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "purpleair_aqi_pm2_5_10_minute{conversion=\"None\"}",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "Temperature History",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    { "expr": "purpleair_temp_f - 8", "legendFormat": "{{label}}" }
   ]
  },
  {
   "title": "Humidity History",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "clamp_max(purpleair_humidity + 4, 100)",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "Pressure History",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "purpleair_pressure", "legendFormat": "{{label}}" }
   ]
  }
 ]
}