name: build and publish

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.5.2

      - uses: docker/metadata-action@v4.3.0
        id: docker_meta
        with:
          images: |
            nirajsanghvi/purpleair_scraper
            ghcr.io/nirajsanghvi/purpleair_scraper
          tags: |
            type=semver,pattern={{version}}

      - uses: docker/login-action@v2.1.0
        with:
          username: nirajsanghvi
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/setup-buildx-action@v2.5.0

      - uses: docker/build-push-action@v4.0.0
        with:
          build-args: --progress plain
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}, nirajsanghvi/purpleair_scraper
          labels: ${{ steps.docker_meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
